language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

install:
  - ./travis-init.sh
  - composer install -n

script:
  - ./vendor/bin/phpunit --coverage-text
